In [1]:
import numpy as np

In [2]:
# First 20 countries with employment data
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

In [8]:
# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])

In [4]:
# Accessing elements
if True:
    print countries[0]
    print countries[3]

Afghanistan
Angola


In [5]:
# Slicing
if True:
    print countries[0:3]
    print countries[:3]
    print countries[17:]
    print countries[:]

['Afghanistan' 'Albania' 'Algeria']
['Afghanistan' 'Albania' 'Algeria']
['Bhutan' 'Bolivia' 'Bosnia and Herzegovina']
['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Argentina' 'Armenia'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina']


In [6]:
# Element types
if True:
    print countries.dtype
    print employment.dtype
    print np.array([0, 1, 2, 3]).dtype
    print np.array([1.0, 1.5, 2.0, 2.5]).dtype
    print np.array([True, False, True]).dtype
    print np.array(['AL', 'AK', 'AZ', 'AR', 'CA']).dtype

|S22
float64
int32
float64
bool
|S2


In [7]:
# Looping
if True:
    for country in countries:
        print 'Examining country {}'.format(country)

    for i in range(len(countries)):
        country = countries[i]
        country_employment = employment[i]
        print 'Country {} has employment {}'.format(country,
                country_employment)

Examining country Afghanistan
Examining country Albania
Examining country Algeria
Examining country Angola
Examining country Argentina
Examining country Armenia
Examining country Australia
Examining country Austria
Examining country Azerbaijan
Examining country Bahamas
Examining country Bahrain
Examining country Bangladesh
Examining country Barbados
Examining country Belarus
Examining country Belgium
Examining country Belize
Examining country Benin
Examining country Bhutan
Examining country Bolivia
Examining country Bosnia and Herzegovina
Country Afghanistan has employment 55.70000076
Country Albania has employment 51.40000153
Country Algeria has employment 50.5
Country Angola has employment 75.69999695
Country Argentina has employment 58.40000153
Country Armenia has employment 40.09999847
Country Australia has employment 61.5
Country Austria has employment 57.09999847
Country Azerbaijan has employment 60.90000153
Country Bahamas has employment 66.59999847
Country Bahrain has employmen

In [9]:
# Numpy functions
if True:
    print employment.mean()
    print employment.std()
    print employment.max()
    print employment.sum()

58.6850000385
9.33826911369
75.69999695
1173.70000077


In [15]:
max_value = employment.max()

i_array = np.argwhere(employment == max_value)

i_array

array([[3]])

In [17]:
i_array[0][0]

3

In [20]:
countries[3]

'Angola'

In [ ]:
def max_employment0(countries, employment):
    max_country = None
    max_value = 0
    
    for i in range(len(countries)):
        country = countries[i]
        country_employment = employment[i]
        
        if country_employment > max_value:
            max_country = country
            max_value = country_employment
            
    return (max_country, max_value)

In [10]:
def max_employment(countries, employment):
    '''
    Fill in this function to return the name of the country
    with the highest employment in the given employment
    data, and the employment in that country.
    '''
    
    max_value = employment.max()   # Replace this with your code
    
    i_2d_array = np.argwhere(employment == max_value)
    i = i_2d_array[0][0]

    max_country = countries[i]
    
    return (max_country, max_value)

In [ ]:
def max_employment2(countries, employment):
    i = employment.argmax()
    return (countries[i], employment[i])

In [21]:
array_1 = np.array([0, 1, 2])

array_1

array([0, 1, 2])

In [1]:
import numpy as np

# Change False to True for each block of code to see what it does

# Arithmetic operations between 2 NumPy arrays
if True:
    a = np.array([1, 2, 3, 4])
    b = np.array([1, 2, 1, 2])
    
    print a + b
    print a - b
    print a * b
    print a / b
    print a ** b

[2 4 4 6]
[0 0 2 2]
[1 4 3 8]
[1 1 3 2]
[ 1  4  3 16]


In [2]:
# Arithmetic operations between a NumPy array and a single number
if True:
    a = np.array([1, 2, 3, 4])
    b = 2
    
    print a + b
    print a - b
    print a * b
    print a / b
    print a ** b

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0 1 1 2]
[ 1  4  9 16]


In [8]:
a = np.array([1, 2, 3, 4])
b = 2.

print a / b

[ 0.5  1.   1.5  2. ]


In [3]:
# Logical operations with NumPy arrays
if True:
    a = np.array([True, True, False, False])
    b = np.array([True, False, True, False])
    
    print a & b # T,F,F,F
    print a | b # T,T,T,F
    print ~a # F,F,T,T
    
    print a & True # A
    print a & False # F,f,f,f
    
    print a | True # T,T,T,T
    print a | False #  A

[ True False False False]
[ True  True  True False]
[False False  True  True]
[ True  True False False]
[False False False False]
[ True  True  True  True]
[ True  True False False]


In [4]:
# Comparison operations between 2 NumPy Arrays
if True:
    a = np.array([1, 2, 3, 4, 5])
    b = np.array([5, 4, 3, 2, 1])
    
    print a > b # 0,0,0,1,1
    print a >= b # 0,0,1,1,1
    print a < b # 1,1,0,0,0
    print a <= b # 1,1,1,0,0
    print a == b # 0,0,1,0,0
    print a != b # 1,1,0,1,1

[False False False  True  True]
[False False  True  True  True]
[ True  True False False False]
[ True  True  True False False]
[False False  True False False]
[ True  True False  True  True]


In [5]:
# First 20 countries with school completion data
countries = np.array([
       'Algeria', 'Argentina', 'Armenia', 'Aruba', 'Austria','Azerbaijan',
       'Bahamas', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Bolivia',
       'Botswana', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cambodia', 'Cameroon', 'Cape Verde'
])

In [6]:
# Female school completion rate in 2007 for those 20 countries
female_completion = np.array([
    97.35583,  104.62379,  103.02998,   95.14321,  103.69019,
    98.49185,  100.88828,   95.43974,   92.11484,   91.54804,
    95.98029,   98.22902,   96.12179,  119.28105,   97.84627,
    29.07386,   38.41644,   90.70509,   51.7478 ,   95.45072
])

In [7]:
# Male school completion rate in 2007 for those 20 countries
male_completion = np.array([
     95.47622,  100.66476,   99.7926 ,   91.48936,  103.22096,
     97.80458,  103.81398,   88.11736,   93.55611,   87.76347,
    102.45714,   98.73953,   92.22388,  115.3892 ,   98.70502,
     37.00692,   45.39401,   91.22084,   62.42028,   90.66958
])

In [ ]:
def overall_completion_rate(female_completion, male_completion):
    '''
    Fill in this function to return a NumPy array containing the overall
    school completion rate for each country. The arguments are NumPy
    arrays giving the female and male completion of each country in
    the same order.
    '''
    sum_completion = female_completion + male_completion
    
    female_completion_rate = female_completion / sum_completion
    male_completion_rate = male_completion / sum_completion
    
    return (male_completion_rate, female_completion_rate)

In [9]:
def overall_completion_rate(female_completion, male_completion):
    '''
    Fill in this function to return a NumPy array containing the overall
    school completion rate for each country. The arguments are NumPy
    arrays giving the female and male completion of each country in
    the same order.
    '''
    sum_completion = female_completion + male_completion
    return sum_completion / 2.0

In [10]:
# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])

In [13]:
# Change this country name to change what country will be printed when you
# click "Test Run". Your function will be called to determine the standardized
# score for this country for each of the given 5 Gapminder variables in 2007.
# The possible country names are available in the Downloadables section.

country_name = 'United States'

def standardize_data(values):
    '''
    Fill in this function to return a standardized version of the given values,
    which will be in a NumPy array. Each value should be translated into the
    number of standard deviations that value is away from the mean of the data.
    (A positive number indicates a value higher than the mean, and a negative
    number indicates a value lower than the mean.)
    '''
    standardize_values = (values - values.mean()) / values.std()
    
    return standardize_values

## Numpy index arrays

In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([True, True, False, True])

print a[b]
print a[np.array([True, False, True, False])]

[1 2 4]
[1 3]


In [15]:
a = np.array([1, 2, 3, 2, 1])
b = (a > 2)

print a[b]
print a[a >= 2]

[3]
[2 3 2]


In [16]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 2, 1])

print b == 2 # 0,1,0,1,0
print a[b == 2] # [2,4]

[False  True False  True False]
[2 4]


In [17]:
def mean_time_for_paid_students(time_spent, days_to_cancel):
    '''
    Fill in this function to calculate the mean time spent in the classroom
    for students who stayed enrolled at least (greater than or equal to) 7 days.
    Unlike in Lesson 1, you can assume that days_to_cancel will contain only
    integers (there are no students who have not canceled yet).
    
    The arguments are NumPy arrays. time_spent contains the amount of time spent
    in the classroom for each student, and days_to_cancel contains the number
    of days until each student cancel. The data is given in the same order
    in both arrays.
    '''
    time_spent_more_7_days = time_spent[days_to_cancel >= 7]
    mean_time = time_spent_more_7_days.mean()
    return mean_time

In [18]:
# Time spent in the classroom in the first week for 20 students
time_spent = np.array([
       12.89697233,    0.        ,   64.55043217,    0.        ,
       24.2315615 ,   39.991625  ,    0.        ,    0.        ,
      147.20683783,    0.        ,    0.        ,    0.        ,
       45.18261617,  157.60454283,  133.2434615 ,   52.85000767,
        0.        ,   54.9204785 ,   26.78142417,    0.
])

# Days to cancel for 20 students
days_to_cancel = np.array([
      4,   5,  37,   3,  12,   4,  35,  38,   5,  37,   3,   3,  68,
     38,  98,   2, 249,   2, 127,  35
])

In [19]:
mean_time_for_paid_students(time_spent, days_to_cancel)

41.054003485454537

## + vs +=

## In-place vs Not In-place

# Pandas Series

In [21]:
import pandas as pd

countries = ['Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda',
             'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
             'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
             'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia']

life_expectancy_values = [74.7,  75. ,  83.4,  57.6,  74.6,  75.4,  72.3,  81.5,  80.2,
                          70.3,  72.1,  76.4,  68.1,  75.2,  69.8,  79.4,  70.8,  62.7,
                          67.3,  70.6]

gdp_values = [ 1681.61390973,   2155.48523109,  21495.80508273,    562.98768478,
              13495.1274663 ,   9388.68852258,   1424.19056199,  24765.54890176,
              27036.48733192,   1945.63754911,  21721.61840978,  13373.21993972,
                483.97086804,   9783.98417323,   2253.46411147,  25034.66692293,
               3680.91642923,    366.04496652,   1175.92638695,   1132.21387981]

In [22]:
# Life expectancy and gdp data in 2007 for 20 countries
life_expectancy = pd.Series(life_expectancy_values)
gdp = pd.Series(gdp_values)

In [23]:
print life_expectancy[0]

74.7


In [24]:
print gdp[3:6]

3      562.987685
4    13495.127466
5     9388.688523
dtype: float64


In [25]:
for country_life_expectancy in life_expectancy:
    print "examing life expectancy {0}".format(country_life_expectancy)

examing life expectancy 74.7
examing life expectancy 75.0
examing life expectancy 83.4
examing life expectancy 57.6
examing life expectancy 74.6
examing life expectancy 75.4
examing life expectancy 72.3
examing life expectancy 81.5
examing life expectancy 80.2
examing life expectancy 70.3
examing life expectancy 72.1
examing life expectancy 76.4
examing life expectancy 68.1
examing life expectancy 75.2
examing life expectancy 69.8
examing life expectancy 79.4
examing life expectancy 70.8
examing life expectancy 62.7
examing life expectancy 67.3
examing life expectancy 70.6


In [26]:
print life_expectancy.mean()
print life_expectancy.std()

72.87
6.21399947487


In [27]:
print gdp.max()
print gdp.min()

27036.4873319
366.04496652


In [28]:
a = pd.Series([1, 2, 3, 4])
b = pd.Series([1, 2, 3, 4])

print a + b

0    2
1    4
2    6
3    8
dtype: int64


In [29]:
print a * 2

0    2
1    4
2    6
3    8
dtype: int64


In [30]:
print a >= 3

0    False
1    False
2     True
3     True
dtype: bool


In [31]:
print a[a >= 3]

2    3
3    4
dtype: int64


In [35]:
a = [True, True]
b = [True, False]

print a + b

[True, True, True, False]


In [38]:
def variable_correlation(variable1, variable2):
    '''
    Fill in this function to calculate the number of data points for which
    the directions of variable1 and variable2 relative to the mean are the
    same, and the number of data points for which they are different.
    Direction here means whether each value is above or below its mean.
    
    You can classify cases where the value is equal to the mean for one or
    both variables however you like.
    
    Each argument will be a Pandas series.
    
    '''
    both_above = (variable1 > variable1.mean()) & (variable2 > variable2.mean())
    both_below = (variable1 < variable1.mean()) & (variable2 < variable2.mean())
    
    is_same_direction = both_above | both_below
    num_same_direction = is_same_direction.sum()
    
    num_different_direction = len(variable1) - num_same_direction

    return (num_same_direction, num_different_direction)

In [39]:
variable_correlation(life_expectancy, gdp)

(17, 3)