In [1]:
import pandas as pd

nyc_subway_weather = pd.read_csv('datasets/nyc_subway_weather.csv')

In [3]:
nyc_subway_weather.head(5)

UNIT     DATEn     TIMEn  ENTRIESn   EXITSn  ENTRIESn_hourly  \
0  R003  05-01-11  00:00:00   4388333  2911002                0   
1  R003  05-01-11  04:00:00   4388333  2911002                0   
2  R003  05-01-11  12:00:00   4388333  2911002                0   
3  R003  05-01-11  16:00:00   4388333  2911002                0   
4  R003  05-01-11  20:00:00   4388333  2911002                0   

   EXITSn_hourly             datetime  hour  day_week     ...       pressurei  \
0              0  2011-05-01 00:00:00     0         6     ...           30.22   
1              0  2011-05-01 04:00:00     4         6     ...           30.25   
2              0  2011-05-01 12:00:00    12         6     ...           30.28   
3              0  2011-05-01 16:00:00    16         6     ...           30.26   
4              0  2011-05-01 20:00:00    20         6     ...           30.28   

  rain  tempi  wspdi meanprecipi  meanpressurei  meantempi  meanwspdi  \
0    0   55.9    3.5           0         30.258      55.98       7.86   
1    0   52.0    3.5           0         30.258      55.98       7.86   
2    0   62.1    6.9           0         30.258      55.98       7.86   
3    0   57.9   15.0           0         30.258      55.98       7.86   
4    0   52.0   10.4           0         30.258      55.98       7.86   

   weather_lat  weather_lon  
0    40.700348   -73.887177  
1    40.700348   -73.887177  
2    40.700348   -73.887177  
3    40.700348   -73.887177  
4    40.700348   -73.887177  

[5 rows x 27 columns]

## 2D Numpy Array

In [1]:
import numpy as np

# Subway ridership for 5 stations on 10 different days 10*5
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [2]:
print ridership[1, 3]

2328


In [3]:
print ridership[1:3, 3:5]

[[2328 2539]
 [6461 2691]]


In [4]:
print ridership[1, :]

[1478 3877 3674 2328 2539]


In [5]:
print ridership[0, :] + ridership[1, :]

[1478 3877 3676 2333 2539]


In [6]:
print ridership[:, 0] + ridership[:, 1]

[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


In [7]:
a = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
b = np.array([
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]
    ])

print a + b

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [9]:
idx = ridership[0, :].argmax()

print idx

3


In [10]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    1 - max_riders_1st_day_station
    2 - return mean_rider_per_day_of_that-station
    3 - return the mean ridership overall
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
    ''' 
    overall_mean = ridership.mean()
    
    max_station_idx = ridership[0, :].argmax()
    mean_for_max = ridership[:, max_station_idx].mean()
    
    return (overall_mean, mean_for_max)

In [11]:
mean_riders_for_max_station(ridership)

(2342.5999999999999, 3239.9000000000001)

## Numpy axis

In [12]:
print a.sum()

45


In [13]:
print a.sum(axis=0)

[12 15 18]


In [14]:
print a.sum(axis=1)

[ 6 15 24]


In [16]:
def min_and_max_riders_per_day(ridership):
    '''
    Fill in this function. First, for each subway station, calculate the
    mean ridership per day. Then, out of all the subway stations, return the
    maximum and minimum of these values. That is, find the maximum
    mean-ridership-per-day and the minimum mean-ridership-per-day for any
    subway station.
    '''
    # mean ridership per day of each subway station
    # max and min of these mean ridership

    mean_ridership_perday_each_station = ridership.mean(axis=0)
    
    max_daily_ridership = mean_ridership_perday_each_station.max()     # Replace this with your code
    min_daily_ridership = mean_ridership_perday_each_station.min()     # Replace this with your code
    
    return (max_daily_ridership, min_daily_ridership)

In [17]:
min_and_max_riders_per_day(ridership)

(3239.9000000000001, 1071.2)

In [18]:
emrollment = np.array([
        ['account_key', 'status', 'days_to_cancel'],
        ['448', 'canceled', 65],
        ['448', 'canceled', 10]
    ])

In [19]:
emrollment

array([['account_key', 'status', 'days_to_cancel'],
       ['448', 'canceled', '65'],
       ['448', 'canceled', '10']], 
      dtype='|S14')

### Note the dtype, the number became strings, 65--> '65', 10 --> '10'

In [20]:
import pandas as pd

# Subway ridership for 5 stations on 10 different days
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)

In [29]:
ridership_df

R003  R004  R005  R006  R007
05-01-11     0     0     2     5     0
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613
05-05-11  1608  4802  3932  4477  2705
05-06-11  1576  3933  3909  4979  2685
05-07-11    95   229   255   496   201
05-08-11     2     0     1    27     0
05-09-11  1438  3785  3589  4174  2215
05-10-11  1342  4043  4009  4665  3033

## # DataFrame creation

In [22]:
df_1 = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})

print df_1

   A  B
0  0  3
1  1  4
2  2  5


In [23]:
df_1

A  B
0  0  3
1  1  4
2  2  5

In [24]:
df_2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns=['A', 'B', 'C'
    ])
print df_2

   A  B  C
0  0  1  2
1  3  4  5


In [25]:
df_2

A  B  C
0  0  1  2
1  3  4  5

## Accessing elements

In [26]:
print ridership_df.iloc[0] # 1st row

R003    0
R004    0
R005    2
R006    5
R007    0
Name: 05-01-11, dtype: int64


In [27]:
print ridership_df.loc['05-06-11']

R003    1576
R004    3933
R005    3909
R006    4979
R007    2685
Name: 05-06-11, dtype: int64


In [28]:
print ridership_df[
    'R006'
]

05-01-11       5
05-02-11    2328
05-03-11    6461
05-04-11    4787
05-05-11    4477
05-06-11    4979
05-07-11     496
05-08-11      27
05-09-11    4174
05-10-11    4665
Name: R006, dtype: int64


In [31]:
print ridership_df.iloc[0, 3]

5


### Accessing multiple rows

In [32]:
print ridership_df.iloc[1:4]

          R003  R004  R005  R006  R007
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613


### Accessing multiple columns

In [33]:
print ridership_df[['R003', 'R005']]

          R003  R005
05-01-11     0     2
05-02-11  1478  3674
05-03-11  1613  3991
05-04-11  1560  3826
05-05-11  1608  3932
05-06-11  1576  3909
05-07-11    95   255
05-08-11     2     1
05-09-11  1438  3589
05-10-11  1342  4009


In [35]:
df = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})

In [36]:
df

A  B
0  0  3
1  1  4
2  2  5

In [37]:
print df.sum()

A     3
B    12
dtype: int64


In [38]:
print df.sum(axis=0)

A     3
B    12
dtype: int64


In [39]:
print df.sum(axis=1)

0    3
1    5
2    7
dtype: int64


In [40]:
print df.values

[[0 3]
 [1 4]
 [2 5]]


In [41]:
print df.values.sum()

15


In [43]:
max_station = ridership_df.iloc[0].argmax()

print max_station

R006


In [48]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    This is the same as a previous exercise, but this time the
    input is a Pandas DataFrame rather than a 2D NumPy array.
    '''
    max_station = ridership.iloc[0].argmax()
    overall_mean = ridership.values.mean() # Replace this with your code
    mean_for_max = ridership[max_station].mean() # Replace this with your code
    
    return (overall_mean, mean_for_max)

In [49]:
mean_riders_for_max_station(ridership_df)

(2342.5999999999999, 3239.9)

## Calculating Correlation

http://www.mathsisfun.com/data/correlation.html

In [51]:
filename = 'datasets/nyc_subway_weather.csv'
subway_df = pd.read_csv(filename)

In [52]:
subway_df.head()

UNIT     DATEn     TIMEn  ENTRIESn   EXITSn  ENTRIESn_hourly  \
0  R003  05-01-11  00:00:00   4388333  2911002                0   
1  R003  05-01-11  04:00:00   4388333  2911002                0   
2  R003  05-01-11  12:00:00   4388333  2911002                0   
3  R003  05-01-11  16:00:00   4388333  2911002                0   
4  R003  05-01-11  20:00:00   4388333  2911002                0   

   EXITSn_hourly             datetime  hour  day_week     ...       pressurei  \
0              0  2011-05-01 00:00:00     0         6     ...           30.22   
1              0  2011-05-01 04:00:00     4         6     ...           30.25   
2              0  2011-05-01 12:00:00    12         6     ...           30.28   
3              0  2011-05-01 16:00:00    16         6     ...           30.26   
4              0  2011-05-01 20:00:00    20         6     ...           30.28   

  rain  tempi  wspdi meanprecipi  meanpressurei  meantempi  meanwspdi  \
0    0   55.9    3.5           0         30.258      55.98       7.86   
1    0   52.0    3.5           0         30.258      55.98       7.86   
2    0   62.1    6.9           0         30.258      55.98       7.86   
3    0   57.9   15.0           0         30.258      55.98       7.86   
4    0   52.0   10.4           0         30.258      55.98       7.86   

   weather_lat  weather_lon  
0    40.700348   -73.887177  
1    40.700348   -73.887177  
2    40.700348   -73.887177  
3    40.700348   -73.887177  
4    40.700348   -73.887177  

[5 rows x 27 columns]

In [57]:
def correlation(x, y):
    '''
    Fill in this function to compute the correlation between the two
    input variables. Each input is either a NumPy array or a Pandas
    Series.
    
    correlation = average of (x in standard units) times (y in standard units)
    
    Remember to pass the argument "ddof=0" to the Pandas std() function!
    '''
    
    std_x = (x - x.mean()) / x.std(ddof=0)
    std_y = (y - y.mean()) / y.std(ddof=0)
       
    correlation = (std_x * std_y).mean()
    return correlation

In [58]:
entries = subway_df['ENTRIESn_hourly']
cum_entries = subway_df['ENTRIESn']
rain = subway_df['meanprecipi']
temp = subway_df['meantempi']

In [59]:
print correlation(entries, rain)

0.0356485157722


In [60]:
print correlation(entries, temp)

-0.0266933483216


In [61]:
print correlation(entries, cum_entries)

0.585895470766
