## intro

> 1  NumPy provides a multidimensional array object that support optimized vector operations.

> 2 SciPy offers a wide variety of scientific algorithms(signal processing, optimization, and so on)that are based on NumPy.

> 3 Pandas proposed convenient data structures for tabular data coming form real world data set.

> 4 Matplotlib allows to plot graphical figures easily so as to visualize interactively any form of data, and to generate pubilcation-quality
> figures.

> 5 IPython provide the adequate interactive framework for using all these tools in a streamlined way.

from IPython minibook

## Interactive data analysis with pandas
reference:
    https://github.com/ipython-books/minibook-2nd-code#2-interactive-data-analysis-with-pandas

so 数据从何而来？   
网页？  
下载？

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = pd.read_csv(url, names=names)

In [8]:
data.head(10)

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1
5     5   116    74     0     0  25.6  0.201   30      0
6     3    78    50    32    88  31.0  0.248   26      1
7    10   115     0     0     0  35.3  0.134   29      0
8     2   197    70    45   543  30.5  0.158   53      1
9     8   125    96     0     0   0.0  0.232   54      1

In [9]:
data.columns

Index([u'preg', u'plas', u'pres', u'skin', u'test', u'mass', u'pedi', u'age',
       u'class'],
      dtype='object')

In [10]:
d_preg = data.preg

In [11]:
d_preg

0       6
1       1
2       8
3       1
4       0
5       5
6       3
7      10
8       2
9       8
10      4
11     10
12     10
13      1
14      5
15      7
16      0
17      7
18      1
19      1
20      3
21      8
22      7
23      9
24     11
25     10
26      7
27      1
28     13
29      5
       ..
738     2
739     1
740    11
741     3
742     1
743     9
744    13
745    12
746     1
747     1
748     3
749     6
750     4
751     1
752     3
753     0
754     8
755     1
756     7
757     0
758     1
759     6
760     2
761     9
762     9
763    10
764     2
765     5
766     1
767     1
Name: preg, dtype: int64

# Chapter 3. Numerical Computing with IPython

## 1.0 什么是 array？
### 1.1 reimplementing the example with arrays

## 2 Creating and load arrays

### 2.1 creating arrays

- from scratch, element by element   
- from scratch, using predefined templates   
- from random values   

### 2.2 Loading arrays

- from a native Python object   
- from a buffer or an external file   
- using pandas

## 3 Working with arrays

- selection   
- manipulation     
- compulation  

### 3.1 Selection

- using Pandas   
- using NumPy     
- More indexing possibilities   

### 3.2 Manipulation

- reshaping   
- Repeating and concatenating    
- Broadcasting   
- Permuting

### 3.3 Computation

+ - ...

## 4 Advanced mathematical processing

further reading 
- (http://docs.scipy.org/doc/scipy/reference/)    
- NumPy Cookbook, Ivan Idris, Packt Publishing    
- Learning SciPy for Numerical and Scientific Computing, Francisco Blanco-Silva, Packt Publishing

about:
    
- **Linear algebra routines** are provided by the scipy.linalg subpackage   
- **Optimization routines** are provided by the scipy.optimize subpackage   
- **Numerical integrators** are provided by the scipy.integrate subpackage   
- **Signal processing** algorithms are implemented in the scipy.signal subpackage     
- **Statistical routines** are provided by the scipy.stats subpackage  

In [13]:
# this is the function to search the (interest position)in positions regard to target position 
def closest(target_position, positions):
    x0, y0 = target_position
    dbest, ibest = None, None
    for i, (x, y) in enumerate(positions):
        d = (x - x0) ** 2 + (y - y0) ** 2
        if dbest is None or d < dbest:
            dbest, ibest = d, i
    return ibest

In [14]:
import random
positions = [(random.random(), random.random()) for _ in xrange(10000)]

In [16]:
%timeit closest((.5, .5), positions)

100 loops, best of 3: 11.8 ms per loop


这个算法用了11.8ms来处理10,000个位置数据。

## 1.0 什么是 array？

- 1维 array 是个向量
- 2维 array 是个矩阵
- n维 array 呢？

> an n-dimensional array is a set of elements with the same data type that are indexed by a tuple of n integers

如果是3维的可以想想一个3*3的魔方吧， 每个小块放一个数字。或者就是在一个三维坐标系中，一个点自身包含一个坐标

一个 array 中 每个元素的类型都是相同的 data type (dtype)

Numpy 中的数据类型

- Booleans
- signed/unsigned intergers
- single-precison/double-precison floating point numbers
- complex numbers
- strings...

> custom data types can also be defined

那么可以自定义自己的数据类型。

啊哈，每个 array 元素存放在存储器中的啊 那必须啊
那么如何store呢？

对于一个矩阵：

- row-major order (C-order)的方式存储 先存一行再存下一行的数据
- column-major order (Fort an-order) 的方式存储，先存第一列的数据，再存第二列...

这就取决于 在array的元素 哪个的index走的快。 我的理解就是，2*2的矩阵，那么选 c-order or Fort an-order 一样咯
2*3 的就不不一样了。

在NumPy中 默认的方式是 C-order， 可以修改， 通过关键词 order.

> This notion can be extended to any number of dimensions.

步长了吧

>　The stride defines the number of steps in each dimension that are made as one goes through all elements.

array 的好处 计算更加快了，想想用矩阵来替代loop那

> The advantage of arrays compared with native Python types is that it is possible to perform very efficient computations on arrays 
instead of relying on Python loops.  
> The difference is that the loop is implemented internally in C by NumPy instead of Python, so that there is no longer the cost of 
interpretation within the loop.Indeed, Python being an interpreted, dynamically-typed language, each iteration involves various 
low-level operations performed by Python (type checking and so on). Those operations generally take negligible time, but they become 
noxious to performance when they are repeated millions of times.

2016.4.27.10:56pm

### 1.1 reimplementing the example with arrays

using magic command %pylab （或者也可以 在Ipython中 使用 ipython --pylab） instead of   

- import numpy   
- import numpy as np   
- from numpy import *   

let's get started

In [2]:
%pylab

Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib


In [3]:
# two dimensional array with 10,000 rows and 2 columns 随机数 服从0-1区间的 独立均匀分布
# 这也就取代了 for loop
positions = rand(10000,2)

In [4]:
type(positions)

numpy.ndarray

In [5]:
positions.ndim, positions.shape
# 看维数 .ndim
# 看有几行几列的 .shape

(2, (10000, 2))

- the **shape** attribute contains the array shape as a tuple of integers  
- **ndim**: the number of dimensions, = len(positions.shape)    
- **size**: 元素总数
- **itemsize**: the size in bytes of each element (four for and **int32** data type, eight for **float64**, and so on)

In [6]:
positions

array([[ 0.80536932,  0.47722834],
       [ 0.46274451,  0.48181636],
       [ 0.94546656,  0.57698629],
       ..., 
       [ 0.91957357,  0.20178375],
       [ 0.60934585,  0.81861987],
       [ 0.99874259,  0.27066044]])

In [9]:
x, y = positions[:,0], positions[0,1]

In [11]:
distances = (x - .5) ** 2 + (y - .5) ** 2

In [12]:
distances.shape

(10000,)

In [13]:
distances.ndim

1

In [14]:
type(distances)

numpy.ndarray

In [15]:
%timeit ibest = distances.argmin()

100000 loops, best of 3: 17.6 µs per loop


和上面的 （100 loops, best of 3: 11.8 ms per loop） 相比 计算时间都不再一个数量级的啊 使用array形式的时间量级为微秒，而之前一个为ms

## 2 creating and loading arrays

自定义

In [17]:
x = array([1, 2, 3])

In [18]:
x

array([1, 2, 3])

In [19]:
x.shape

(3,)

In [20]:
x.dtype

dtype('int32')

以上是 一维 的 array 默认 32-bit intergers

In [21]:
x = array([1, 2, 3], dtype=float64)

In [22]:
x.dtype

dtype('float64')

In [23]:
array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
def mul_1(n):
    return array([[(i + 1) * (j + 1) for i in xrange(n)] for j in xrange(n)])

In [25]:
mul_1(4)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [27]:
%timeit mul_1(100)

100 loops, best of 3: 3.69 ms per loop


使用已有的functions

In [30]:
x = zeros(100)

In [31]:
x

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [32]:
x = zeros((10,10))

In [34]:
x.dtype

dtype('float64')

其他的有

- ones
- identity
- eye
- diag

In [35]:
arange(2, 10 ,2) # linspace 

array([2, 4, 6, 8])

与 matlab相似

In [36]:
help(arange)

Help on built-in function arange in module numpy.core.multiarray:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
    but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use ``linspace`` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and

随机数

In [37]:
rand(2, 5)

array([[ 0.89239321,  0.80498392,  0.69392113,  0.5773781 ,  0.55901177],
       [ 0.65549711,  0.46740208,  0.42451206,  0.9120011 ,  0.7237161 ]])

修改数值精度

In [39]:
%precision 3

u'%.3f'

In [40]:
rand(2,4)

array([[ 0.424,  0.581,  0.632,  0.711],
       [ 0.108,  0.659,  0.786,  0.835]])

In [41]:
%precision?

In [42]:
randn(2,4) # random values sampled from a Gaussian distribution

array([[ 2.662,  2.131, -0.667, -0.479],
       [ 0.723,  0.034, -1.626, -0.876]])

In [46]:
help(randint)

Help on built-in function randint:

randint(...)
    randint(low, high=None, size=None)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution in the
    "half-open" interval [`low`, `high`). If `high` is None (the default),
    then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is the *highest* such
        integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    

In [47]:
randint(5)

1

In [48]:
randint(10, size=(3,4))

array([[0, 3, 1, 1],
       [9, 9, 7, 3],
       [9, 8, 4, 8]])

### Loading arrays

In [49]:
np.fromstring('1 2 4 11', dtype=int, sep=' ')

array([ 1,  2,  4, 11])

- frombuffer   
- fromstring   
- fromfile   
- loadtxt   
- genfromtxt

#### using pandas

In [50]:
import pandas
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

data = pandas.read_csv(url, names=names)

In [51]:
data

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
5       5   116    74     0     0  25.6  0.201   30      0
6       3    78    50    32    88  31.0  0.248   26      1
7      10   115     0     0     0  35.3  0.134   29      0
8       2   197    70    45   543  30.5  0.158   53      1
9       8   125    96     0     0   0.0  0.232   54      1
10      4   110    92     0     0  37.6  0.191   30      0
11     10   168    74     0     0  38.0  0.537   34      1
12     10   139    80     0     0  27.1  1.441   57      0
13      1   189    60    23   846  30.1  0.398   59      1
14      5   166    72    19   175  25.8  0.587   51      1
15      7   100     0     0     0  30.0  0.484   32      1
16      0   118    84    47   230  45.8  0.551   31      1
17      7   107    74     0     0  29.6  0.254   31      1
18      1   103    30    38    83  43.3  0.183   33      0
19      1   115    70    30    96  34.6  0.529   32      1
20      3   126    88    41   235  39.3  0.704   27      0
21      8    99    84     0     0  35.4  0.388   50      0
22      7   196    90     0     0  39.8  0.451   41      1
23      9   119    80    35     0  29.0  0.263   29      1
24     11   143    94    33   146  36.6  0.254   51      1
25     10   125    70    26   115  31.1  0.205   41      1
26      7   147    76     0     0  39.4  0.257   43      1
27      1    97    66    15   140  23.2  0.487   22      0
28     13   145    82    19   110  22.2  0.245   57      0
29      5   117    92     0     0  34.1  0.337   38      0
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
738     2    99    60    17   160  36.6  0.453   21      0
739     1   102    74     0     0  39.5  0.293   42      1
740    11   120    80    37   150  42.3  0.785   48      1
741     3   102    44    20    94  30.8  0.400   26      0
742     1   109    58    18   116  28.5  0.219   22      0
743     9   140    94     0     0  32.7  0.734   45      1
744    13   153    88    37   140  40.6  1.174   39      0
745    12   100    84    33   105  30.0  0.488   46      0
746     1   147    94    41     0  49.3  0.358   27      1
747     1    81    74    41    57  46.3  1.096   32      0
748     3   187    70    22   200  36.4  0.408   36      1
749     6   162    62     0     0  24.3  0.178   50      1
750     4   136    70     0     0  31.2  1.182   22      1
751     1   121    78    39    74  39.0  0.261   28      0
752     3   108    62    24     0  26.0  0.223   25      0
753     0   181    88    44   510  43.3  0.222   26      1
754     8   154    78    32     0  32.4  0.443   45      1
755     1   128    88    39   110  36.5  1.057   37      1
756     7   137    90    41     0  32.0  0.391   39      0
757     0   123    72     0     0  36.3  0.258   52      1
758     1   106    76     0     0  37.5  0.197   26      0
759     6   190    92     0     0  35.5  0.278   66      1
760     2    88    58    26    16  28.4  0.766   22      0
761     9   170    74    31     0  44.0  0.403   43      1
762     9    89    62     0     0  22.5  0.142   33      0
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [52]:
data.shape

(768, 9)

In [53]:
data.size

6912

In [54]:
data.ndim

2

In [55]:
data.keys() # return the names of the different columns

Index([u'preg', u'plas', u'pres', u'skin', u'test', u'mass', u'pedi', u'age',
       u'class'],
      dtype='object')

In [56]:
data.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [57]:
data.head(3)

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1

In [58]:
data.tail(3)

preg  plas  pres  skin  test  mass   pedi  age  class
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

In [59]:
data.tail()

preg  plas  pres  skin  test  mass   pedi  age  class
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

## 3 working with arrays

In [60]:
data.test

0        0
1        0
2        0
3       94
4      168
5        0
6       88
7        0
8      543
9        0
10       0
11       0
12       0
13     846
14     175
15       0
16     230
17       0
18      83
19      96
20     235
21       0
22       0
23       0
24     146
25     115
26       0
27     140
28     110
29       0
      ... 
738    160
739      0
740    150
741     94
742    116
743      0
744    140
745    105
746      0
747     57
748    200
749      0
750      0
751     74
752      0
753    510
754      0
755    110
756      0
757      0
758      0
759      0
760     16
761      0
762      0
763    180
764      0
765    112
766      0
767      0
Name: test, dtype: int64

In [61]:
data.test[765]

112

In [62]:
data.test[0]

0

In [63]:
type(data.test)

pandas.core.series.Series

In [64]:
data[data.test==0]

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
5       5   116    74     0     0  25.6  0.201   30      0
7      10   115     0     0     0  35.3  0.134   29      0
9       8   125    96     0     0   0.0  0.232   54      1
10      4   110    92     0     0  37.6  0.191   30      0
11     10   168    74     0     0  38.0  0.537   34      1
12     10   139    80     0     0  27.1  1.441   57      0
15      7   100     0     0     0  30.0  0.484   32      1
17      7   107    74     0     0  29.6  0.254   31      1
21      8    99    84     0     0  35.4  0.388   50      0
22      7   196    90     0     0  39.8  0.451   41      1
23      9   119    80    35     0  29.0  0.263   29      1
26      7   147    76     0     0  39.4  0.257   43      1
29      5   117    92     0     0  34.1  0.337   38      0
30      5   109    75    26     0  36.0  0.546   60      0
33      6    92    92     0     0  19.9  0.188   28      0
34     10   122    78    31     0  27.6  0.512   45      0
36     11   138    76     0     0  33.2  0.420   35      0
37      9   102    76    37     0  32.9  0.665   46      1
38      2    90    68    42     0  38.2  0.503   27      1
41      7   133    84     0     0  40.2  0.696   37      0
42      7   106    92    18     0  22.7  0.235   48      0
44      7   159    64     0     0  27.4  0.294   40      0
45      0   180    66    39     0  42.0  1.893   25      1
46      1   146    56     0     0  29.7  0.564   29      0
47      2    71    70    27     0  28.0  0.586   22      0
48      7   103    66    32     0  39.1  0.344   31      1
49      7   105     0     0     0   0.0  0.305   24      0
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
712    10   129    62    36     0  41.2  0.441   38      1
714     3   102    74     0     0  29.5  0.121   32      0
717    10    94    72    18     0  23.1  0.595   56      0
719     5    97    76    27     0  35.6  0.378   52      1
720     4    83    86    19     0  29.3  0.317   34      0
724     1   111    94     0     0  32.8  0.265   45      0
725     4   112    78    40     0  39.4  0.236   38      0
727     0   141    84    26     0  32.4  0.433   22      0
728     2   175    88     0     0  22.9  0.326   22      0
729     2    92    52     0     0  30.1  0.141   22      0
731     8   120    86     0     0  28.4  0.259   22      1
734     2   105    75     0     0  23.3  0.560   53      0
735     4    95    60    32     0  35.4  0.284   28      0
737     8    65    72    23     0  32.0  0.600   42      0
739     1   102    74     0     0  39.5  0.293   42      1
743     9   140    94     0     0  32.7  0.734   45      1
746     1   147    94    41     0  49.3  0.358   27      1
749     6   162    62     0     0  24.3  0.178   50      1
750     4   136    70     0     0  31.2  1.182   22      1
752     3   108    62    24     0  26.0  0.223   25      0
754     8   154    78    32     0  32.4  0.443   45      1
756     7   137    90    41     0  32.0  0.391   39      0
757     0   123    72     0     0  36.3  0.258   52      1
758     1   106    76     0     0  37.5  0.197   26      0
759     6   190    92     0     0  35.5  0.278   66      1
761     9   170    74    31     0  44.0  0.403   43      1
762     9    89    62     0     0  22.5  0.142   33      0
764     2   122    70    27     0  36.8  0.340   27      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[374 rows x 9 columns]

In [65]:
data.ix[0]

preg       6.000
plas     148.000
pres      72.000
skin      35.000
test       0.000
mass      33.600
pedi       0.627
age       50.000
class      1.000
Name: 0, dtype: float64

In [67]:
test = array(data.test)

In [68]:
test.shape

(768,)

In [69]:
test[0]

0

In [70]:
isnan(test)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [71]:
x = rand(5)

In [72]:
x

array([ 0.007,  0.389,  0.591,  0.231,  0.164])

In [74]:
y = x[::3]

In [75]:
y

array([ 0.007,  0.231])

In [78]:
y = x[::2]

In [79]:
y

array([ 0.007,  0.591,  0.164])

In [80]:
y[0]

0.007

In [81]:
y[0] = 1

In [82]:
y

array([ 1.   ,  0.591,  0.164])

In [83]:
x

array([ 1.   ,  0.389,  0.591,  0.231,  0.164])

In [84]:
# fancy indexing
ind = [0, 1, 0, 2]

In [85]:
x[ind] # out x[ind[0], x[ind[1]], x....

array([ 1.   ,  0.389,  1.   ,  0.591])

### manipulation and reshaped

In [86]:
x = rand(6)

In [87]:
x

array([ 0.52 ,  0.76 ,  0.065,  0.804,  0.137,  0.834])

In [88]:
x.reshape((2, 3))

array([[ 0.52 ,  0.76 ,  0.065],
       [ 0.804,  0.137,  0.834]])

1 维的向量  
二维的矩阵   
3 维的坐标系  

In [89]:
x.reshape((2, -1))

array([[ 0.52 ,  0.76 ,  0.065],
       [ 0.804,  0.137,  0.834]])

other:
    
    ravel   
    squeeze   
    expand_dims  

In [90]:
x = arange(3)

In [91]:
x

array([0, 1, 2])

In [92]:
tile(x, (2,1))

array([[0, 1, 2],
       [0, 1, 2]])

In [93]:
repeat(x, 2)

array([0, 0, 1, 1, 2, 2])

In [95]:
z = repeat(x, 4)

In [96]:
z

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

In [97]:
z.reshape(3,4)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [102]:
def mul2(n):
    M = arange(1, n + 1).reshape((-1, 1))
    M = tile(M, (1, n))
    N = arange(1, n + 1).reshape((1, -1))
    N = tile(N, (n, 1))
    return M, N, M * N

In [104]:
mul2(3)

(array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]), array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), array([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]]))

M * N 是对应的元素和元素相乘  
那？矩阵相乘怎么办？？？

In [105]:
def mul3(n):
    M = arange(1, n + 1).reshape((-1, 1))
    M = tile(M, (1, n))
    N = arange(1, n + 1).reshape((1, -1))
    N = tile(N, (n, 1))
    return M, N, M ** N

In [106]:
mul3(3)

(array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]), array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), array([[ 1,  1,  1],
        [ 2,  4,  8],
        [ 3,  9, 27]]))

还是只是对应的各个元素 相 ** 指数 m^n

其他一些操作和matlab中的类似

time： 2016.04.29